### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by MatthewQuRui** [zhaoyiran924/Adv-In-Context-Learning#1]
Hello,

I hope this message finds you well. Your work has been incredibly helpful to me. I wanted to inquire about the expected timeline for the release of the source code. Could you please provide an estimate for when it will be made available to the public?

Thank you very much.

Best regards,

QuRui Zhang

**Comment by zhaoyiran924** [comment]
Thanks so much for your interest in our work! We're cleaning the code and will release it in one week. Sorry, we're busy with EMNLP these days, so the release is postponed to some extent.

**Comment by MatthewQuRui** [comment]
Thank you for the update! I appreciate your efforts. Looking forward to the release whenever it's ready. Good luck with EMNLP!
