### ISSUE TITLE
Request for the code repository of the paper "How do Large Language Models Handle Multilingualism?"

### ISSUE THREAD

**Issue by xiabo0816** [zhaoyiran924/Adv-In-Context-Learning#4]
**I am very sorry for asking other questions in this git repository.**

Recently, I have been conducting research on the multilingual capabilities of large language models.

I was fortunate to read your paper at [https://arxiv.org/pdf/2402.18815v1], from which I have gained great inspiration. However, when I tried to access the code repository mentioned in the paper at [https://github.com/DAMO-NLP-SG/multilingual_analysis], I found that it is currently inaccessible.

Here, I take the liberty to request a copy of the source code that can reproduce the experiments. I am fully aware that your time is extremely precious. But this source code is of crucial importance to my research. I will cherish and use it properly. I would be extremely grateful if you could provide me with this help.

Once again, thanks for your contributions to the field of multilingual large language models!

Best wishes!

**Comment by zhaoyiran924** [comment]
Thank you for your interest in our work. We're excited to announce that we've just received permission to open source our project, adhering to our company's data confidentiality policy. Please take a look, and if you have any questions, feel free to contact us.
