### ISSUE TITLE
Code for How do Large Language Models Handle Multilingualism? paper

### ISSUE THREAD

**Issue by natriistorm** [zhaoyiran924/Adv-In-Context-Learning#5]
Hello, I've seen the similar issue about it, but as the issue contained no answer, I've decided to opne the similar issue. 

As a study project, me and my teammates have been conducting research on the multilingual capabilities of large language models. Your paper [https://arxiv.org/pdf/2402.18815v1] seemed as a very interesting research and we would like to replicate your experiments. However, the code for it is still inaccessible [https://github.com/DAMO-NLP-SG/multilingual_analysis].

We would be very grateful if you could provide a copy of the source code that can reproduce the experiments. Of course we will use it properly and solely to test it on our own dataset.

Once again, thank for your contribution to the field of multilingual large language models and really hoping you would be able to help

Kind regards,
Anastasia

**Comment by zhaoyiran924** [comment]
Thank you for your interest in our work. We're excited to announce that we've just received permission to open source our project, adhering to our company's data confidentiality policy. Please take a look, and if you have any questions, feel free to contact us.
